turtlebot3: #namespace

    task_and_robot_environment_name: 'TurtleBot3World-v0'
    ros_ws_abspath: "/home/ubuntu/simulation_ws"
    running_step: 0.04 # amount of time the control will be executed
    pos_step: 0.016     # increment in position for each command
    
    #dqn parameters
    gamma: 0.999
    epsilon_start: 0.9  #epsilon: (exploration) random choice factor
    epsilon_end: 0.05
    epsilon_decay: 2000
    n_episodes: 3000
    target_update: 10
    batch_size: 128
    learning_rate: 0.001
    max_episode_steps: 500
    
    # Checkpoint Loading Parameters
    resume_from_checkpoint: true  # Set to true to resume training from a saved model
    checkpoint_file: "final_model.pth"  # Which checkpoint to load (default: best_model.pth)

    running_step: 0.06 # Time for each step

